// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AzureKeyVault is an autogenerated mock type for the AzureKeyVault type
type AzureKeyVault struct {
	mock.Mock
}

// GetSecrets provides a mock function with given fields: vaultName
func (_m *AzureKeyVault) GetSecrets(vaultName string) map[string]interface{} {
	ret := _m.Called(vaultName)

	if len(ret) == 0 {
		panic("no return value specified for GetSecrets")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(vaultName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// NewAzureKeyVault creates a new instance of AzureKeyVault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAzureKeyVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *AzureKeyVault {
	mock := &AzureKeyVault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
