// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GcpSecretsManager is an autogenerated mock type for the GcpSecretsManager type
type GcpSecretsManager struct {
	mock.Mock
}

// GetSecret provides a mock function with given fields: secretName
func (_m *GcpSecretsManager) GetSecret(secretName string) map[string]interface{} {
	ret := _m.Called(secretName)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(secretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

type mockConstructorTestingTNewGcpSecretsManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewGcpSecretsManager creates a new instance of GcpSecretsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGcpSecretsManager(t mockConstructorTestingTNewGcpSecretsManager) *GcpSecretsManager {
	mock := &GcpSecretsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
