// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecretsManager is an autogenerated mock type for the SecretsManager type
type SecretsManager struct {
	mock.Mock
}

// GetSecret provides a mock function with given fields: secretName, timeout
func (_m *SecretsManager) GetSecret(secretName string, timeout int) map[string]interface{} {
	ret := _m.Called(secretName, timeout)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string, int) map[string]interface{}); ok {
		r0 = rf(secretName, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// NewSecretsManager creates a new instance of SecretsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsManager {
	mock := &SecretsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
