// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecretsManager is an autogenerated mock type for the SecretsManager type
type SecretsManager struct {
	mock.Mock
}

// GetSecret provides a mock function with given fields: secretName
func (_m *SecretsManager) GetSecret(secretName string) map[string]interface{} {
	ret := _m.Called(secretName)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(secretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

type mockConstructorTestingTNewSecretsManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewSecretsManager creates a new instance of SecretsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecretsManager(t mockConstructorTestingTNewSecretsManager) *SecretsManager {
	mock := &SecretsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
