// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Vault is an autogenerated mock type for the Vault type
type Vault struct {
	mock.Mock
}

// GetSecret provides a mock function with given fields: secretName
func (_m *Vault) GetSecret(secretName string) map[string]interface{} {
	ret := _m.Called(secretName)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(secretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// NewVault creates a new instance of Vault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *Vault {
	mock := &Vault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
