name: Build Package
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G104 ./...

  test:
    needs: gosec
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Check go mod tidy
        run: go mod tidy && git diff --exit-code go.mod go.sum
      - name: Test
        run: go test ./...
